Insert into ELE_PARAMETROS (ID,NOMBRE,VALOR,OBSERVACION,ESTADO,TIPO) values (1,'Ambiente','Pruebas','El código que conformará el tipo de ambiente según la clave de acceso: Pruebas = 1, Producción = 2','Activo','SRI');
Insert into ELE_PARAMETROS (ID,NOMBRE,VALOR,OBSERVACION,ESTADO,TIPO) values (2,'Emisión','Normal','El código que conformará el tipo de emisión según la clave de acceso: Emisión Normal = 1','Activo','SRI');
Insert into ELE_PARAMETROS (ID,NOMBRE,VALOR,OBSERVACION,ESTADO,TIPO) values (3,'Generado','/app/Quijotelui/comprobante/generado','La ubicación donde se genera el archivo XML','Activo','SRI');
Insert into ELE_PARAMETROS (ID,NOMBRE,VALOR,OBSERVACION,ESTADO,TIPO) values (4,'Firmado','/app/Quijotelui/comprobante/firmado','La ubicación donde se genera el archivo XML firmado electrónicamente','Activo','SRI');
Insert into ELE_PARAMETROS (ID,NOMBRE,VALOR,OBSERVACION,ESTADO,TIPO) values (5,'Enviado','/app/Quijotelui/comprobante/enviado','La ubicación donde se copia el archivo XML enviado','Activo','SRI');
Insert into ELE_PARAMETROS (ID,NOMBRE,VALOR,OBSERVACION,ESTADO,TIPO) values (6,'Autorizado','/app/Quijotelui/comprobante/autorizado','La ubicación donde se genera el archivo XML autorizado','Activo','SRI');
Insert into ELE_PARAMETROS (ID,NOMBRE,VALOR,OBSERVACION,ESTADO,TIPO) values (7,'NoAutorizado','/app/Quijotelui/comprobante/noAutorizado','La ubicación donde se genera el archivo XML no autorizado','Activo','SRI');
Insert into ELE_PARAMETROS (ID,NOMBRE,VALOR,OBSERVACION,ESTADO,TIPO) values (8,'Rechazado','/app/Quijotelui/comprobante/rechazado','La ubicación donde se genera el archivo XML rechazado','Activo','SRI');
Insert into ELE_PARAMETROS (ID,NOMBRE,VALOR,OBSERVACION,ESTADO,TIPO) values (9,'PDF','/app/Quijotelui/comprobante/pdf','La ubicación donde se genera el archivo PDF','Activo','SRI');
Insert into ELE_PARAMETROS (ID,NOMBRE,VALOR,OBSERVACION,ESTADO,TIPO) values (10,'Firma Electrónica','/data/BCE/QuijoteLui.p12','Es la ubicación del archivo de la firma electrónica','Activo','CERTIFICADO');
Insert into ELE_PARAMETROS (ID,NOMBRE,VALOR,OBSERVACION,ESTADO,TIPO) values (11,'Clave Firma Electrónica','***************==','Es la contraseña de la firma electrónica','Activo','CERTIFICADO');
Insert into ELE_PARAMETROS (ID,NOMBRE,VALOR,OBSERVACION,ESTADO,TIPO) values (12,'Web Service Recepción','https://celcer.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline?wsdl','Servicio Web del SRI para la recepción de comprobantes electrónicos','Activo','SRI');
Insert into ELE_PARAMETROS (ID,NOMBRE,VALOR,OBSERVACION,ESTADO,TIPO) values (13,'Web Service Autorización','https://celcer.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline?wsdl','Servicio Web del SRI para la autorización de comprobantes electrónicos','Activo','SRI');
Insert into ELE_PARAMETROS (ID,NOMBRE,VALOR,OBSERVACION,ESTADO,TIPO) values (14,'Logo','/app/Quijotelui/recursos/imagenes/logo.jpeg','Es la ubicación del archivo JPEG del logotipo','Activo','SRI');
Insert into ELE_PARAMETROS (ID,NOMBRE,VALOR,OBSERVACION,ESTADO,TIPO) values (15,'Reportes','/app/Quijotelui/recursos/reportes','Es la ubicación de los archivos de reportes','Activo','SRI');
Insert into ELE_PARAMETROS (ID,NOMBRE,VALOR,OBSERVACION,ESTADO,TIPO) values (16,'Servidor Correo','smtp.googlemail.com','Es la dirección del servidor de correo','Activo','CORREO');
Insert into ELE_PARAMETROS (ID,NOMBRE,VALOR,OBSERVACION,ESTADO,TIPO) values (17,'Puerto Servidor Correo','465','Es el número de puerto del servidor de correo','Activo','CORREO');
Insert into ELE_PARAMETROS (ID,NOMBRE,VALOR,OBSERVACION,ESTADO,TIPO) values (18,'Correo','jl@gmail.com','Es la dirección de correo electrónico','Activo','CORREO');
Insert into ELE_PARAMETROS (ID,NOMBRE,VALOR,OBSERVACION,ESTADO,TIPO) values (19,'Clave Correo','***************==','Es la clave de la dirección de correo electrónico','Activo','CORREO');
Insert into ELE_PARAMETROS (ID,NOMBRE,VALOR,OBSERVACION,ESTADO,TIPO) values (20,'Suscripción (aaaa-mm-dd)','**************==','Suscripción','Activo','SUSCRIPCIÓN');
Insert into ELE_PARAMETROS (ID,NOMBRE,VALOR,OBSERVACION,ESTADO,TIPO) values (21,'Correo de cuenta','jl@gmail.com','Suscripción','Activo','SUSCRIPCIÓN');
Insert into ELE_PARAMETROS (ID,NOMBRE,VALOR,OBSERVACION,ESTADO,TIPO) values (22,'Clave de cuenta','****************','Suscripción','Activo','SUSCRIPCIÓN');
Insert into ELE_PARAMETROS (ID,NOMBRE,VALOR,OBSERVACION,ESTADO,TIPO) values (23,'Organización','Ideas en Binario','Suscripción','Activo','SUSCRIPCIÓN');
